### ISSUE TITLE
Feature 1 : Registration 

### ISSUE THREAD

**Issue by selvianu** [fresher-batch-2021/giftshopapp-angular#1]
**User Story**  : By providing proper data, user should be able to register.
Spelling mistake
![image](https://user-images.githubusercontent.com/22638364/129470156-8a88c1d6-e098-4702-8da7-bb2e25a7f581.png)

**Comment by yeswanth1570** [comment]
issuse corrected

**Comment by yeswanth1570** [comment]
issue corrected
